os: windows

language: rust

cache: cargo

rust:
  - 1.28.0
  - stable

before_script:
  - choco install -y python3 --version 3.6.5
  - cargo install bindgen --version 0.43.1
script:
  - upstream/build.sh
  - cargo check --all-targets --features strict
  - cargo test

matrix:
  include:
    - rust: nightly
      before_script:
        - choco install -y python3 --version 3.6.5
        - cargo install bindgen --version 0.43.1
        - rustup component add rustfmt-preview
      script:
        - upstream/build.sh
        - cargo check --all-targets --features strict
        - cargo test
        - cargo fmt -- --check
        - cargo rustdoc -- --deny warnings
